### ISSUE TITLE
Fehler im HTML auf der Website

### ISSUE THREAD

**Issue by MKr4zy** [RainerGa/CCMT#8]
Am Ende des FAQ Bereiches wird ein `</p>` angezeigt.
Ich kann nicht sagen ob es so gewollt ist, oder ob sich das da ungewollt reingeschlichen hat.

**Comment by MKr4zy** [comment]
Wenn ich die Website herunterlade, ist es Zeile 156:
`&lt;/p&gt;`

**Comment by RainerGa** [comment]
Fehler behoben.
